// console.log("Derrota")
// console.log("Derrota")
// console.log("Derrota")
// console.log("Derrota")
// console.log("Derrota")
console.log("Derrota")
console.log("Derrota")
console.log("Derrota")
console.log("Derrota")
console.log("Derrota")
